### ISSUE TITLE
attach finished meme to the save to local storage button

### ISSUE THREAD

**Issue by CyberEthan** [EBOX26/Meme-generator#14]

**Comment by MisterHouse** [comment]
I need to request to make a change in HTML file to wrap <div id="quote-display" class = "text-overlay"> and <div class ="display_images"> in one <div id ="finalPicture"> to rendering content from that div using canvas

**Comment by MisterHouse** [comment]
I guess we need to wrap two div's `<div id="quote-display" class="text-overlay">&<div class = `"display_images">` in one wrap like this `<div id ="finalPicture`> to allow the canvas rendering one div that include picture and text on it.
